Namirnice2/Controllers/FileUploadController.cs
using Namirnice2.Models;
using Namirnice2.Repository;
using PagedList;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace Namirnice2.Controllers
{
    public class FileUploadController : Controller
    {

        private IUploadFile fileUploadRepo = new FileUploadRepo();

        // GET: FileUpload
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "Naziv_desc" : "";
            ViewBag.TrenutnaKolicinaSortParm = sortOrder == "Trenutna_Kolicina" ? "Trenutna_Kolicina_desc" : "Trenutna_Kolicina";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var uploadovaniFajlovi = from s in fileUploadRepo.GetAll()
                           select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                uploadovaniFajlovi = uploadovaniFajlovi.Where(s => s.Naziv.Contains(searchString)
                                       || s.Opis.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "Naziv_desc":
                    uploadovaniFajlovi = uploadovaniFajlovi.OrderByDescending(s => s.Naziv);
                    break;
                case "Trenutna_Kolicina":
                    uploadovaniFajlovi = uploadovaniFajlovi.OrderBy(s => s.TrenutnaKolicina);
                    break;
                case "Trenutna_Kolicina_desc":
                    uploadovaniFajlovi = uploadovaniFajlovi.OrderByDescending(s => s.TrenutnaKolicina);
                    break;
                default:  // Name ascending 
                    uploadovaniFajlovi = uploadovaniFajlovi.OrderBy(s => s.Naziv);
                    break;
            }

            int pageSize = 7;
            int pageNumber = (page ?? 1);
            return View(uploadovaniFajlovi.ToPagedList(pageNumber, pageSize));

            //var sviFajlovi = fileUploadRepo.GetAll();



            //return View(sviFajlovi);
                       
        }


        

        public ActionResult Details(int id)
        {
            FileUploadModel fileUploadModel = new FileUploadModel();
            fileUploadModel = fileUploadRepo.GetById(id);
            return View(fileUploadModel);
        }

        [HttpGet]
        public ActionResult Create()
        {

            return View();
        }
        [HttpPost]
        public ActionResult Create(HttpPostedFileBase fileUploaded, FileUploadModel fileUploadModel)
        {

            if (ModelState.IsValid)
            {
                try
                {
                    /*&& fileUploadModel.Naziv!=null&&fileUploadModel.Opis!=null&&fileUploadModel.Cena<0*/

                    if (fileUploaded != null)
                    {
                        string fileName = Path.GetFileName(fileUploaded.FileName);
                        string extension = Path.GetExtension(fileUploaded.FileName);
                        fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                        fileUploadModel.fileUploaded = "~/UploadedFiles/" + fileName;

                        fileName = Path.Combine(Server.MapPath("~/UploadedFiles"), fileName);

                        fileUploaded.SaveAs(fileName);

                        fileUploadRepo.Add(fileUploadModel);

                        ModelState.Clear();

                        ViewBag.ImageUrl = "UploadedFiles/" + fileName;



                    }
                    ViewBag.FileStatus = "File uploaded successfully.";
                }
                catch (Exception)
                {

                    ViewBag.FileStatus = "Error while file uploading.";
                }

            }
            return RedirectToAction("Index");
        }
        public ActionResult Delete(int id)
        {
            var fajlZaBrisanje = fileUploadRepo.GetById(id);
            if (fajlZaBrisanje != null)
            {
                fileUploadRepo.Delete(fajlZaBrisanje);

                return RedirectToAction("Index");
            }

            ViewBag.FileStatus = "Error while deleting file.";
            return RedirectToAction("Index");

        }
        [HttpGet]
        public ActionResult Edit(int id)
        {

            var data = fileUploadRepo.GetById(id);
            FileUploadModel fileUploadModel = new FileUploadModel
            {
                Id = data.Id,
                Naziv = data.Naziv,
                Opis = data.Opis,
                Cena = data.Cena,
                ZahtevanaKolicina = data.ZahtevanaKolicina,
                TrenutnaKolicina = data.TrenutnaKolicina,
                Razlika = data.Razlika,
                fileUploaded = data.fileUploaded
            };
            return View(fileUploadModel);
        }
        [HttpPost]
        public ActionResult Edit(int id,HttpPostedFileBase fileUploaded, FileUploadModel fileUploadModel)
        {
            
            FileUploadRepo fileUploadRepo = new FileUploadRepo();
            //if (ModelState.IsValid)
            //{
            //    var image = fileUploadRepo.GetById(id);
            //    //if (image == null)
            //    //{
            //    //    return new HttpNotFoundResult();
            //    //}

            //    image.Naziv = fileUploadModel.Naziv;
            //    image.Cena = fileUploadModel.Cena;
            //    image.Opis = fileUploadModel.Opis;
            //    image.ZahtevanaKolicina = fileUploadModel.ZahtevanaKolicina;
            //    image.TrenutnaKolicina = fileUploadModel.TrenutnaKolicina;
            //    image.Razlika = fileUploadModel.Razlika;
            //    image.fileUploaded = fileUploadModel.fileUploaded;
            //}
            ModelState.Clear();

            if (ModelState.IsValid)
            {
                try
                {
                    /*&& fileUploadModel.Naziv!=null&&fileUploadModel.Opis!=null&&fileUploadModel.Cena<0*/

                    if (fileUploaded != null)
                    {
                        string fileName = Path.GetFileName(fileUploaded.FileName);
                        string extension = Path.GetExtension(fileUploaded.FileName);
                        fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                        fileUploadModel.fileUploaded = "~/UploadedFiles/" + fileName;

                        fileName = Path.Combine(Server.MapPath("~/UploadedFiles"), fileName);

                        fileUploaded.SaveAs(fileName);

                        //fileUploadRepo.Add(fileUploadModel);
                        fileUploadRepo.Update(fileUploadModel);



                        ModelState.Clear();

                        ViewBag.ImageUrl = "UploadedFiles/" + fileName;



                    }
                    ViewBag.FileStatus = "File uploaded successfully.";
                }
                catch (Exception)
                {

                    ViewBag.FileStatus = "Error while file uploading.";
                }

                //fileUploadRepo.Update(fileUploadModel);

                return RedirectToAction("Index");
            }

            return View(fileUploadModel);

        }
    }
}

Namirnice2/Views/FileUpload/Create.cshtml
@model Namirnice2.Models.FileUploadModel

@{
                /**/

                ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "FileUpload", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal" >
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.fileUploaded, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fileUploaded, new { htmlAttributes = new { @class = "form-control", @type = "file" } })
                @Html.ValidationMessageFor(model => model.fileUploaded, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" >
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Upload" class="btn btn-primary" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10 text-success">
                @ViewBag.FileStatus
            </div>
        </div>
    </div>
    

    <div class="form-group"  >
        @Html.LabelFor(model => model.Naziv, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Naziv, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Naziv, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Cena, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Cena, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Cena, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Opis, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Opis, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Opis, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ZahtevanaKolicina, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ZahtevanaKolicina, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ZahtevanaKolicina, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TrenutnaKolicina, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TrenutnaKolicina, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TrenutnaKolicina, "", new { @class = "text-danger" })
        </div>
    </div>

   

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>

}
<br /><br /><br />



<div>
    @Html.ActionLink("Back to List", "Index")
</div>
<link rel="stylesheet" href="~/Scripts/Stilovi.css" />

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Namirnice2/Views/FileUpload/Details.cshtml
@model Namirnice2.Models.FileUploadModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div >
    <h4>Detalji o proizvodu:</h4>
    <hr />
    <dl class="dl-horizontal">
        <dd>
            
         <img src="@Url.Content(Model.fileUploaded)" with="250" height="250" />
          

        </dd>
        
        <dt>
            @Html.DisplayNameFor(model => model.Naziv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Naziv)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cena)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cena)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Opis)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Opis)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ZahtevanaKolicina)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ZahtevanaKolicina)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TrenutnaKolicina)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TrenutnaKolicina)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Razlika)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Razlika)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>
<link rel="stylesheet" href="~/Scripts/Stilovi.css" />

Namirnice2/Views/FileUpload/Edit.cshtml
@model Namirnice2.Models.FileUploadModel

@{
                /**/

                ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "FileUpload", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal" >
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.fileUploaded, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fileUploaded, new { htmlAttributes = new { @class = "form-control", @type = "file" } })
                @Html.ValidationMessageFor(model => model.fileUploaded, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Upload" class="btn btn-primary" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10 text-success">
                @ViewBag.FileStatus
            </div>
        </div>
    @*</div>*@

    @*<div class="form-horizontal">*@
        <h4>Podaci o proizvodu:</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        @*<div class="form-group" visibility="hidden" >
            @Html.LabelFor(model => model.fileUploaded, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fileUploaded, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fileUploaded, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Naziv, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Naziv, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Naziv, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cena, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cena, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cena, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Opis, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Opis, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Opis, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ZahtevanaKolicina, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ZahtevanaKolicina, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ZahtevanaKolicina, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TrenutnaKolicina, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TrenutnaKolicina, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TrenutnaKolicina, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Razlika, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Razlika, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Razlika, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<link rel="stylesheet" href="~/Scripts/Stilovi.css" />

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Namirnice2/Views/FileUpload/Index.cshtml
@model PagedList.IPagedList<Namirnice2.Models.FileUploadModel>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@*<link rel="stylesheet" href="Stilovi.css"/>*@


@{
    /**/

    ViewBag.Title = "Index";
}



<h2>Index</h2>

<p>
    <a href="/FileUpload/Create">Dodaj novi artikal</a>
</p>


@using (Html.BeginForm("Index", "FileUpload", FormMethod.Get))
{
    <p>
        Find by name: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Search" />
    </p>
}

<table class="table" >
    <tr>
        <th id="b1">
            Slika Proizvoda
        </th>
        <th id="b2">
            @Html.ActionLink("Naziv", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th id="b3">
            Cena:
        </th>
        <th id="b4">
            Opis:
        </th>
        <th id="b5">
            Zahtevana kolicina:
        </th>
        <th>
            @Html.ActionLink("TrenutnaKolicina", "Index", new { sortOrder = ViewBag.TrenutnaKolicinaSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th id=" b6">
            Razlika:
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            @*<td>
                    @Html.DisplayFor(modelItem => item.fileUploaded)
                </td>*@
            <td>

                <img src="@Url.Content(item.fileUploaded)" with="100" height="100" />

            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Naziv)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cena)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Opis)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ZahtevanaKolicina)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TrenutnaKolicina)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Razlika)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>
<br />
<link rel="stylesheet" href="~/Scripts/Stilovi.css" />

Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))